typedef struct cliente Cliente;
typedef struct vestimenta Vestimenta;
typedef struct locacao Locacao;
char tela_relatorios(void);
void tela_relatorio_clientes(void);
void tela_relatorio_vestimentas(void);
void tela_relatorio_locacoes(char status);
void exibe_cliente(Cliente *cl);
void exibe_vestimenta(Vestimenta *vest);
void exibe_locacao(Locacao *loc, Cliente *cl, Vestimenta *vest);