typedef struct cliente Cliente;
typedef struct vestimenta Vestimenta;
typedef struct locacao Locacao;
int valida_cpf(char cpf[12]);
int valida_nome_pessoa(char nome[81]);
int valida_data(char data[9]);
int valida_telefone(char tel[14]);
int valida_email(char email[81]); 
int valida_nome_vest(char *nome);
int valida_inteiro(char *num);
int valida_float(char *din);
int valida_tamanho_vest(char tam);
int verifica_data_maior(char *data1, char *data2, int inclui_igual);
int bissexto (int ano);
int verifica_exist_cliente(char *cpf);
int verifica_exist_vest(char *id);
int verifica_exist_loc(long id);
int disponibilidade_vest(char *id_vest, char tam_vest);